package compose

import (
	"strings"
	"testing"

	"github.com/gandalfledev/pilot/internal/config"
)

// Distinct project names are what let both stacks coexist: compose scopes
// containers, networks, and its bookkeeping by project.
func TestColorProject(t *testing.T) {
	if got := ColorProject("api", config.ColorBlue); got != "api-blue" {
		t.Errorf("got %q", got)
	}
	if ColorProject("api", config.ColorBlue) == ColorProject("api", config.ColorGreen) {
		t.Error("the two colors must not share a compose project")
	}
}

// Binding to loopback is not tidiness: publishing these to 0.0.0.0 would expose
// both versions of the app directly, bypassing Caddy and its TLS.
func TestRenderOverrideBindsLoopbackOnly(t *testing.T) {
	got := RenderOverride("web", 8080, 18081)

	if !strings.Contains(got, `"127.0.0.1:18081:8080"`) {
		t.Errorf("port mapping wrong:\n%s", got)
	}
	if strings.Contains(got, "0.0.0.0") {
		t.Errorf("must never publish to all interfaces:\n%s", got)
	}
	if !strings.Contains(got, "generated by pilot") {
		t.Error("generated file should say who owns it")
	}
	if !strings.Contains(got, "services:\n  web:") {
		t.Errorf("override should target the named compose service:\n%s", got)
	}
}

func TestOverrideNamePerColor(t *testing.T) {
	blue := overrideName(config.ColorBlue)
	green := overrideName(config.ColorGreen)
	if blue == green {
		t.Fatal("each color needs its own override file")
	}
	for _, n := range []string{blue, green} {
		if !strings.HasPrefix(n, "compose.pilot-") || !strings.HasSuffix(n, ".yaml") {
			t.Errorf("override name %q should be recognisable as Pilot's", n)
		}
	}
}

// The command must name the color's project *and* its override, or the wrong
// stack gets the wrong port.
func TestColorCmdScopesProjectAndOverride(t *testing.T) {
	got := colorCmdFor("/opt/pilot/services/api/releases/0042-abc1234", "api", config.ColorGreen, "up", "--detach")

	for _, want := range []string{
		"--project-name api-green",
		"--file /opt/pilot/services/api/releases/0042-abc1234/compose.yaml",
		"--file /opt/pilot/services/api/releases/0042-abc1234/compose.pilot-green.yaml",
		"up --detach",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
	if strings.Contains(got, "pilot-blue") {
		t.Errorf("green's command must not reference blue's override:\n%s", got)
	}
}

func TestColorCmdOrdersBaseFileBeforeOverride(t *testing.T) {
	got := colorCmdFor("/rel", "api", config.ColorBlue, "up")

	base := strings.Index(got, "/rel/compose.yaml")
	override := strings.Index(got, "/rel/compose.pilot-blue.yaml")
	if base < 0 || override < 0 {
		t.Fatalf("both files should be passed:\n%s", got)
	}
	// Compose merges later files over earlier ones, so the override has to come
	// second or it would not override anything.
	if override < base {
		t.Errorf("override must follow the base compose file:\n%s", got)
	}
}
