package compose

import (
	"context"
	"fmt"
	"path"

	"github.com/gandalfledev/pilot/internal/config"
	"github.com/gandalfledev/pilot/internal/runtime"
	"github.com/gandalfledev/pilot/internal/transport"
)

// ActiveProject returns the compose project actually backing a service.
//
// This is not a detail: under blue-green the containers live in `<svc>-blue` or
// `<svc>-green`, never in `<svc>`. Anything that asks Docker about a service —
// status, logs, fingerprinting, a `docker: true` health check — has to ask
// about the right one, or it will confidently report a running service as
// stopped.
func ActiveProject(ctx context.Context, t *runtime.Target) string {
	if !t.Service.Rollout.IsBlueGreen() {
		return project(t)
	}
	return ColorProject(t.Service.Name, ActiveColor(ctx, t))
}

// ActiveColor reports which color currently serves.
//
// The default is blue so that a service with no recorded state deploys to
// green first, which matches what the agent does.
func ActiveColor(ctx context.Context, t *runtime.Target) config.Color {
	st, err := runtime.ReadState(ctx, t)
	if err != nil || st.ActiveColor == "" {
		return config.ColorBlue
	}
	return config.Color(st.ActiveColor)
}

// ActiveDir returns the release directory and override to use for the live
// color, so a compose invocation resolves the same ports the stack was started
// with.
func activeArgs(ctx context.Context, t *runtime.Target, args ...string) string {
	if !t.Service.Rollout.IsBlueGreen() {
		return cmd(t.CurrentDir(), project(t), args...)
	}
	return colorCmdFor(t.CurrentDir(), t.Service.Name, ActiveColor(ctx, t), args...)
}

// ColorProject is the compose project name for one color.
//
// Distinct project names are what let both stacks exist at once: compose scopes
// containers, networks, and its own bookkeeping by project, so blue and green
// never see each other.
func ColorProject(service string, c config.Color) string {
	return service + "-" + string(c)
}

// RenderOverride produces the compose override pinning a color's host port.
//
// Binding to 127.0.0.1 rather than 0.0.0.0 is deliberate and not merely tidy:
// these ports are an implementation detail of the flip, and publishing them to
// the world would expose both versions of the app directly, bypassing Caddy
// and its TLS entirely.
func RenderOverride(svc string, containerPort, hostPort int) string {
	return fmt.Sprintf(`# generated by pilot — do not edit
# pins this color's host port so Caddy can flip between the two stacks
services:
  %s:
    ports:
      - "127.0.0.1:%d:%d"
`, svc, hostPort, containerPort)
}

// StageColor writes the override for a color into the release directory.
//
// Both colors' overrides are written at stage time so that either can be
// started later from the same release — which is what makes a rollback after
// the flip a matter of starting the other color, not re-staging.
func StageColor(ctx context.Context, t *runtime.Target) error {
	r := t.Service.Rollout
	if !r.IsBlueGreen() {
		return nil
	}
	if t.Service.Expose == nil || t.Service.Expose.Upstream == 0 {
		return fmt.Errorf("blue-green needs `expose.upstream` (the container port)")
	}

	// One file per color, so the port a stack binds is fixed by which override
	// it is started with rather than by anything mutable.
	for _, c := range config.AllColors {
		body := RenderOverride(r.Service, t.Service.Expose.Upstream, r.PortFor(c))
		target := path.Join(t.ReleaseDir(), overrideName(c))
		if err := t.Client.WriteFile(ctx, target, []byte(body), "0644"); err != nil {
			return fmt.Errorf("writing %s override: %w", c, err)
		}
	}
	return nil
}

// overrideName is the per-color override file inside a release.
func overrideName(c config.Color) string {
	return fmt.Sprintf("compose.pilot-%s.yaml", c)
}

// colorCmdFor builds a compose invocation for a color using that color's
// override file.
func colorCmdFor(dir, service string, c config.Color, args ...string) string {
	base := []string{
		"docker", "compose",
		"--project-name", ColorProject(service, c),
		"--project-directory", dir,
		"--file", path.Join(dir, composeFile),
		"--file", path.Join(dir, overrideName(c)),
		"--env-file", path.Join(dir, ".env"),
	}
	return transport.Join(append(base, args...)...)
}

// StartColor brings a color up from a specific release, without touching the
// other color or any routing.
//
// Nothing user-visible happens here: the new stack is running and reachable
// only on its own loopback port until the route is flipped.
func StartColor(ctx context.Context, t *runtime.Target, c config.Color, releaseDir string) error {
	svc := t.Service.Name
	cmd := colorCmdFor(releaseDir, svc, c, "up", "--detach", "--remove-orphans", "--wait=false")

	res, err := t.Client.Run(ctx, cmd)
	if err != nil {
		return err
	}
	if !res.OK() {
		return fmt.Errorf("starting %s (%s): %w", svc, c, res.Err())
	}
	return nil
}

// StopColor takes a color down.
func StopColor(ctx context.Context, t *runtime.Target, c config.Color, releaseDir string) error {
	svc := t.Service.Name
	cmd := colorCmdFor(releaseDir, svc, c, "down", "--remove-orphans")

	res, err := t.Client.Run(ctx, cmd)
	if err != nil {
		return err
	}
	if !res.OK() {
		return fmt.Errorf("stopping %s (%s): %w", svc, c, res.Err())
	}
	return nil
}

// ObserveColor reports the state of one color's stack.
func ObserveColor(ctx context.Context, t *runtime.Target, c config.Color) (runtime.Observation, error) {
	obs := runtime.Observation{State: runtime.StateUnknown}

	cmd := transport.Join("docker", "compose", "--project-name", ColorProject(t.Service.Name, c),
		"ps", "--all", "--format", "json")
	res, err := t.Client.Run(ctx, cmd)
	if err != nil {
		return obs, err
	}
	if !res.OK() {
		obs.Detail = res.Stderr
		return obs, nil
	}

	instances, err := ParsePS([]byte(res.Stdout))
	if err != nil {
		return obs, err
	}
	obs.Instances = instances
	// A color with no containers is stopped, which for the inactive color is
	// the normal resting state rather than a problem.
	obs.State, obs.Detail = summarise(instances, "present")
	return obs, nil
}
