package proto

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/Gandalf-Le-Dev/pilot/internal/config"
)

// goldenPath records the schema as of the pinned digest, so a failure can name
// the field that moved instead of only reporting two hashes.
const goldenPath = "testdata/schema.txt"

// TestSchemaDigestMatchesConfig is the guard that a comment used to be.
//
// The CLI and the agent exchange configuration, so a schema change is a
// protocol change whether or not the wire format moved. This test fails on any
// schema edit and makes you decide which kind it was.
func TestSchemaDigestMatchesConfig(t *testing.T) {
	got := config.SchemaFingerprint()
	if got == SchemaDigest {
		assertGoldenCurrent(t, config.SchemaFields())
		return
	}

	added, removed := diffAgainstGolden(t, config.SchemaFields())

	var b strings.Builder
	b.WriteString("the configuration schema changed\n\n")
	for _, line := range added {
		b.WriteString("    + " + line + "\n")
	}
	for _, line := range removed {
		b.WriteString("    - " + line + "\n")
	}
	if len(added) == 0 && len(removed) == 0 {
		b.WriteString("    (no field-level diff — the golden file may be stale)\n")
	}

	b.WriteString("\nAn agent parses this schema strictly, so a field it does not know is a\n")
	b.WriteString("rejected deploy, not a warning. Decide which change this is:\n\n")
	b.WriteString("  the agent must understand the change (a new or renamed field)\n")
	b.WriteString("      bump Version in proto.go, then update SchemaDigest\n\n")
	b.WriteString("  the agent never decodes it (a field the CLI keeps to itself)\n")
	b.WriteString("      update SchemaDigest alone\n\n")
	b.WriteString("Either way:\n")
	b.WriteString("      SchemaDigest = \"" + got + "\"\n")
	b.WriteString("      go test ./internal/transport/proto -run SchemaDigest -update\n")

	t.Fatal(b.String())
}

// assertGoldenCurrent keeps the record honest while the digest is passing.
//
// Without this the golden file is only ever read on failure, so it can drift
// silently — and it did: it went stale during the notifier work, and the next
// schema change (the systemd unit block) came with a diff listing somebody
// else's fields alongside its own. A diff you have to second-guess is worse
// than no diff, because the whole point is to say "you added expose.allow"
// rather than "something moved".
func assertGoldenCurrent(t *testing.T, current []string) {
	t.Helper()

	if updateGolden {
		writeGolden(t, current)
		return
	}
	added, removed := diffAgainstGolden(t, current)
	if len(added) == 0 && len(removed) == 0 {
		return
	}
	t.Errorf("the digest matches but %s does not describe the current schema:\n"+
		"    + %s\n    - %s\n\n"+
		"refresh it so the next schema change gets a clean diff:\n"+
		"      go test ./internal/transport/proto -run SchemaDigest -update",
		goldenPath, strings.Join(added, "\n    + "), strings.Join(removed, "\n    - "))
}

// diffAgainstGolden reports how the current schema differs from the recorded
// one, refreshing the record when -update is passed.
func diffAgainstGolden(t *testing.T, current []string) (added, removed []string) {
	t.Helper()

	if updateGolden {
		writeGolden(t, current)
		return nil, nil
	}

	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		return nil, nil // no record to compare against
	}
	var previous []string
	for _, line := range strings.Split(string(raw), "\n") {
		if line = strings.TrimSpace(line); line != "" && !strings.HasPrefix(line, "#") {
			previous = append(previous, line)
		}
	}

	for _, line := range current {
		if !slices.Contains(previous, line) {
			added = append(added, line)
		}
	}
	for _, line := range previous {
		if !slices.Contains(current, line) {
			removed = append(removed, line)
		}
	}
	return added, removed
}

func writeGolden(t *testing.T, fields []string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Generated by `go test ./internal/transport/proto -update`.\n" +
		"# The configuration schema pinned by SchemaDigest — do not edit by hand.\n" +
		strings.Join(fields, "\n") + "\n"
	if err := os.WriteFile(goldenPath, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestSchemaFingerprintIsStable guards the fingerprint itself: a digest that
// varied between runs would fail the pin at random and quickly get deleted.
func TestSchemaFingerprintIsStable(t *testing.T) {
	first := config.SchemaFingerprint()
	for range 20 {
		if got := config.SchemaFingerprint(); got != first {
			t.Fatalf("fingerprint is not deterministic: %s then %s", first, got)
		}
	}
	if len(first) != 16 {
		t.Errorf("fingerprint = %q, want 16 hex characters", first)
	}
}

// TestSchemaCoversNestedFields checks the walk actually descends. A fingerprint
// that only saw top-level fields would have missed `expose.allow` — the exact
// change this whole mechanism exists to catch.
func TestSchemaCoversNestedFields(t *testing.T) {
	fields := config.SchemaFields()

	joined := strings.Join(fields, "\n")
	for _, want := range []string{"service.expose", "service.health", "fleet.hosts"} {
		if !strings.Contains(joined, want) {
			t.Errorf("schema does not mention %q — the walk is not descending", want)
		}
	}

	var deep int
	for _, f := range fields {
		if strings.Count(strings.Fields(f)[0], ".") >= 2 {
			deep++
		}
	}
	if deep == 0 {
		t.Error("no field is nested two levels deep; the walk stops too early")
	}
}
